# Generated by Django 4.2.8 on 2023-12-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwscout_app', '0002_remove_jobapplication_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='days_off_per_year',
            field=models.PositiveIntegerField(default=21),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='facilities',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='hours_per_week',
            field=models.PositiveIntegerField(default=21),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='num_open_positions',
            field=models.PositiveIntegerField(default=21),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='open_position',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='salary_per_month',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='subscription_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
