# Generated by Django 4.2.8 on 2023-12-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwscout_app', '0003_jobapplication_days_off_per_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='hours_per_week',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='num_open_positions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
