# Generated by Django 4.2.8 on 2023-12-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wwscout_app', '0004_alter_jobapplication_hours_per_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('position', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('current_country', models.CharField(default='', max_length=100)),
                ('natal_country', models.CharField(default='', max_length=100)),
                ('current_workplace', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
